# Generated by Django 4.2.29 on 2026-04-07 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fii', 'FII'), ('renda_fixa', 'Renda Fixa'), ('cripto', 'Criptomoeda'), ('outro', 'Outro')], max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='aportes.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=15)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes', to='aportes.ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aporte',
                'verbose_name_plural': 'Aportes',
                'ordering': ['-data'],
            },
        ),
    ]
